import uuid
from typing import List
from pydantic import BaseModel, Field


class MinimalSource(BaseModel):
    """
    Represents a specific segment of text within a source file.

    Attributes:
        file_path (str): Path to the source file.
        first_character_index (int): Starting position of the chunk.
        last_character_index (int): Ending position of the chunk.
    """
    file_path: str
    first_character_index: int
    last_character_index: int


class UnansweredQuestion(BaseModel):
    """
    Represents a raw evaluation question before retrieval.

    Attributes:
        question_id (str): Unique identifier for the question.
        question (str): The natural language query.
    """
    question_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    question: str


class AnsweredQuestion(UnansweredQuestion):
    """
    Represents a reference question paired with ground truth.

    Attributes:
        sources (List[MinimalSource]): Ground truth source locations.
        answer (str): The expected ground truth response.
    """
    sources: List[MinimalSource]
    answer: str


class RagDataset(BaseModel):
    """
    A collection holding a list of evaluation dataset questions.

    Attributes:
        rag_questions (List[Union[AnsweredQuestion, UnansweredQuestion]]):
            List containing answered or unanswered question objects.
    """
    rag_questions: List[AnsweredQuestion | UnansweredQuestion]


class MinimalSearchResults(BaseModel):
    """
    Holds the intermediate retrieval result for a specific question.

    Attributes:
        question_id (str): Identifier matching the question.
        question (str): The original natural language question.
        retrieved_sources (List[MinimalSource]): Top-k sources found.
    """
    question_id: str
    question: str
    retrieved_sources: List[MinimalSource]


class MinimalAnswer(MinimalSearchResults):
    """
    Holds the complete search result combined with the LLM answer.

    Attributes:
        answer (str): The response text generated by the model.
    """
    answer: str


class StudentSearchResults(BaseModel):
    """
    Wrapper for the complete batch of search results.

    Attributes:
        search_results (List[MinimalSearchResults]): All processed queries.
        k (int): Number of requested source chunks per query.
    """
    search_results: List[MinimalSearchResults]
    k: int


class StudentSearchResultsAndAnswer(BaseModel):
    """
    Wrapper for the complete batch of answered search results.

    Attributes:
        search_results (List[MinimalAnswer]): All answered queries.
        k (int): Number of requested source chunks per query.
    """
    search_results: List[MinimalAnswer]
    k: int
